"""<descriptive message>

Revision ID: 8d4ae0fd33f2
Revises: fa0f3839956e
Create Date: 2023-06-14 12:26:15.552051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4ae0fd33f2'
down_revision = 'fa0f3839956e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_consumptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_consumptions', schema=None) as batch_op:
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###
