"""<descriptive message>

Revision ID: 9809639e2750
Revises: 8d4ae0fd33f2
Create Date: 2023-06-14 12:33:40.718260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9809639e2750'
down_revision = '8d4ae0fd33f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_consumptions', schema=None) as batch_op:
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_consumptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
