"""create tables

Revision ID: f75d01e622c2
Revises: 
Create Date: 2023-06-13 14:45:58.124313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75d01e622c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('consumption_goal', sa.Integer(), nullable=True),
    sa.Column('ounces_consumed', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_consumptions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ounces', sa.Integer(), nullable=True),
    sa.Column('daily_consumption_id', sa.Integer(), nullable=True),
    sa.Column('drink_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_consumption_id'], ['daily_consumptions.id'], name=op.f('fk_drinks_daily_consumption_id_daily_consumptions')),
    sa.ForeignKeyConstraint(['drink_type_id'], ['drink_types.id'], name=op.f('fk_drinks_drink_type_id_drink_types')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drinks')
    op.drop_table('daily_consumptions')
    op.drop_table('users')
    op.drop_table('drink_types')
    # ### end Alembic commands ###
